apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-yellowhammer-ovh-tls
spec:
  secretName: kubernetes-yellowhammer-ovh
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubernetes.yellowhammer.com
  dnsNames:
    - kubernetes.yellowhammer.com
    - www.kubernetes.yellowhammer.com