  name: Deploy docker images
  on:
    push:
      branches:
        - main
  env:
    SHA: $(git rev-parse HEAD)

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Log in to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
        
        - name: Build test docker image
          run: docker build -t bigyellowhammer/docker-complex-client-dev -f ./client/Dockerfile.dev ./client
        
        - name: Run tests
          run: docker run -e CI=true bigyellowhammer/docker-complex-client-dev npm run test

        - name: Set Service Key
          uses: 'google-github-actions/auth@v0'
          with: 
            credentials_json: '${{ secrets.GKE_SA_KEY}}'
        
        - name: Set Project
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: multi-k8s-403116

        - name: Auth
          run : gcloud --quiet auth configure-docker
        
        - name: Get Credentials
          uses: google-github-actions/get-gke-credentials@v0
          with:
            cluster_name: multi-cluster
            location: us-central1-c

        # - name: Build and Deploy
        #   run: |
        #     bash ${GITHUB_WORKSPACE}/deploy.sh

        - name: Build prod docker image (client)
          run: docker build -t bigyellowhammer/docker-complex-client:latest -t bigyellowhammer/docker-complex-client:${{ env.SHA }} -f ./client/Dockerfile ./client
        - name: Build prod docker image (server)
          run: docker build -t bigyellowhammer/docker-complex-server:latest -t bigyellowhammer/docker-complex-server:${{ env.SHA }} -f ./server/Dockerfile ./server
        - name: Build prod docker image (worker)
          run: docker build -t bigyellowhammer/docker-complex-worker:latest -t bigyellowhammer/docker-complex-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker
        - name: Publish prod docker image (client)
          run: docker push bigyellowhammer/docker-complex-client:${{ env.SHA }}
        - name: Publish prod docker image (client) latest
          run: docker push bigyellowhammer/docker-complex-client:latest
        - name: Publish prod docker image (server)
          run: docker push bigyellowhammer/docker-complex-server:${{ env.SHA }}
        - name: Publish prod docker image (server) latest
          run: docker push bigyellowhammer/docker-complex-server:latest
        - name: Publish prod docker image (worker)
          run: docker push bigyellowhammer/docker-complex-worker:${{ env.SHA }}
        - name: Publish prod docker image (worker) latest
          run: docker push bigyellowhammer/docker-complex-worker:latest

        - name: Apply
          run: |-
            kubectl apply -f k8s
            kubectl set image deployments/server-deployment server=bigyellowhammer/docker-complex-server:${{ env.SHA }}
            kubectl set image deployments/client-deployment client=bigyellowhammer/docker-complex-client:${{ env.SHA }}
            kubectl set image deployments/worker-deployment worker=bigyellowhammer/docker-complex-worker:${{ env.SHA }}

        # - name: Generate deployment package
        #   run: zip -r deploy.zip . -x '*.git*'
        
        # - name: Deploy to AWS Elasticbeanstalk
        #   uses: einaregilsson/beanstalk-deploy@v21
        #   with:
        #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        #     application_name: multi-docker
        #     environment_name: Multi-docker-env-1
        #     existing_bucket_name: elasticbeanstalk-us-east-1-495531827909
        #     region: us-east-1
        #     version_label: ${{ github.sha}}
        #     deployment_package: deploy.zip